server:
  port: 8687

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.136.127:3306/course?serverTimezone=GMT
    username: root
    password: hltx8848

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

